### ISSUE TITLE
CSS Reset 样式重置

### ISSUE THREAD

**Issue by pengbeirong** [pengbeirong/x-tips#10]
CSS reset的作用是让各个浏览器的CSS样式有一个统一的基准，建议每个页面都重置样式。
但是呢，CSS reset的滥用就很严重了。今天看了大神张鑫旭的一篇[CSS reset的重新审视 – 避免样式重置](https://www.zhangxinxu.com/wordpress/2010/04/css-reset%E7%9A%84%E9%87%8D%E6%96%B0%E5%AE%A1%E8%A7%86-%E9%81%BF%E5%85%8D%E6%A0%B7%E5%BC%8F%E9%87%8D%E7%BD%AE/)，受益匪浅啊！

话不多说，直接上代码

``` css
body, dl, dd, h1, h2, h3, h4, h5, h6, p, form {
  margin: 0;
}
button, input, textarea {
  padding: 0;
  border: 0;
}
ol, ul {
  margin: 0; 
  padding: 0;
}
body, div, h1, h2, h3, h4, h5, h6, p, dl, dd, dt, ol, ul, li, textarea, input, button {
  box-sizing: border-box;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  vertical-align: baseline;
  outline: 0;
}
html, body {
  height: 100%;
}
body {
  line-height: 1.5;
  font-size: 14px;
  font-family: 'Helvetica Neue', Helvetica, 'PingFang SC', 'Microsoft YaHei', Arial, sans-serif;
  color: #333;
  background: #fff;
}
ol, ul {
  list-style: none;
}
h1 { 
  font-size: 22px;
}
h2 { 
  font-size: 18px;
}
h3 {
  font-size: 16px;
}
textarea {
  resize: none;
}
a, a:focus, a:hover {
  color: #333;
  text-decoration: none; 
}
i, em { 
  font-style: normal;
}
// chrome自动填充数值样式
input:-webkit-autofill, textarea:-webkit-autofill, select:-webkit-autofill {
  background: 0;
  box-shadow: 0 0 0 1000px white inset;
  -webkit-text-fill-color: #000;
}
// 输入框占位符样式
::placeholder, ::-webkit-input-placeholder {
  color: #ccc;
}
```

以上就是常用标签的重置样式，如有需要添加的标签，可以先去查看文档，看有没有添加的必要
简单的CSS reset样式完成了，如有好的想法/建议，欢迎留言！！！
